classDiagram
    Animal <|-- Dog
    Animal <|-- Cat

    class Animal {
        String nom
        decimal coutNourriture
        int frequenceRepas
        datetime dernierRepas

        void exprimer
        void manger
    }

    class Dog {
        void bark()
    }

    class Cat {
        void meow()
    }
