classDiagram
    Animal <|-- Chien
    Animal <|-- Chat
    Personne "1" --> "1..*" Animal : possède
    Personne "1" --* "1" Compte
    Personne "1" --o "1" Emploi



    class Animal{
        +string nom
        +decimal coutNourriture
        +int frequenceRepas
        +datetime dernierRepas

        +exprimer()
        +manger()
    }

    class Chien{
        +exprimer()
    }

    class Chat{
        +exprimer()
    }

    class Personne{
        +string nom
        +Compte compte
        +Emploi emploi

        +travailler()
        +nourrir()
    }

    class Compte{
        +decimal solde

        +deposer(decimal montant)
        +retirer(decimal montant)
    }

    class Emploi{
        +string titre
        +decimal salaire


    }
